/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CELESTE
 */
public class Interfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(179, 235, 235));
        lblNombreFarmacia.setOpaque(true);
        lblNombreFarmacia.setBackground(java.awt.Color.WHITE);
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Distribuidores = new javax.swing.ButtonGroup();
        lblNombreFarmacia = new javax.swing.JLabel();
        txtmedic = new javax.swing.JTextField();
        ComboBoxTipMedic = new javax.swing.JComboBox<>();
        TextCantidad = new javax.swing.JTextField();
        CheckBoxPrincipal = new javax.swing.JCheckBox();
        CheckBoxSecundaria = new javax.swing.JCheckBox();
        RadioButCofarma = new javax.swing.JRadioButton();
        RadioButEmpsephar = new javax.swing.JRadioButton();
        RadButCemefar = new javax.swing.JRadioButton();
        lblnombremec = new javax.swing.JLabel();
        lblnombretipmedic = new javax.swing.JLabel();
        lblcantidad = new javax.swing.JLabel();
        lbldistribuidor = new javax.swing.JLabel();
        lblsucursal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttborrar = new javax.swing.JButton();
        buttconfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PEDIDOS FARMACIA CELES S.A.S");
        setBackground(new java.awt.Color(179, 235, 235));

        lblNombreFarmacia.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreFarmacia.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNombreFarmacia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreFarmacia.setText("FARMACIA CELESTE S.A.S");
        lblNombreFarmacia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtmedic.setToolTipText("");

        ComboBoxTipMedic.setEditable(true);
        ComboBoxTipMedic.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        ComboBoxTipMedic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "analgésico", "analéptico", "anestésico", "antiácido", "antidepresivo", "antibióticos" }));

        CheckBoxPrincipal.setText("Principal");
        CheckBoxPrincipal.setBorder(null);
        CheckBoxPrincipal.addActionListener(this::CheckBoxPrincipalActionPerformed);

        CheckBoxSecundaria.setText("Secundaria");
        CheckBoxSecundaria.addActionListener(this::CheckBoxSecundariaActionPerformed);

        Distribuidores.add(RadioButCofarma);
        RadioButCofarma.setText("Cofarma");
        RadioButCofarma.addActionListener(this::RadioButCofarmaActionPerformed);

        Distribuidores.add(RadioButEmpsephar);
        RadioButEmpsephar.setText("Empsephar");
        RadioButEmpsephar.addActionListener(this::RadioButEmpsepharActionPerformed);

        Distribuidores.add(RadButCemefar);
        RadButCemefar.setText("Cemefar");

        lblnombremec.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblnombremec.setText("Nombre del Medicamento:");

        lblnombretipmedic.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblnombretipmedic.setText("Tipo de Medicamento:");

        lblcantidad.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblcantidad.setText("Cantidad: ");

        lbldistribuidor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbldistribuidor.setText("Distribuidor:");

        lblsucursal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblsucursal.setText("Sucursal:");

        jSeparator1.setBackground(new java.awt.Color(179, 235, 235));
        jSeparator1.setForeground(new java.awt.Color(179, 235, 235));
        jSeparator1.setToolTipText("");

        buttborrar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        buttborrar.setText("Borrar");
        buttborrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttborrar.addActionListener(this::buttborrarActionPerformed);

        buttconfirmar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        buttconfirmar.setText("Confirmar");
        buttconfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttconfirmar.addActionListener(this::buttconfirmarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreFarmacia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblnombremec)
                                    .addComponent(lblnombretipmedic, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblcantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbldistribuidor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblsucursal, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TextCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                            .addComponent(txtmedic)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(ComboBoxTipMedic, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CheckBoxPrincipal)
                                            .addComponent(RadioButCofarma))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(RadioButEmpsephar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RadButCemefar))
                                            .addComponent(CheckBoxSecundaria)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(buttborrar)
                        .addGap(63, 63, 63)
                        .addComponent(buttconfirmar)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNombreFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmedic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombremec))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxTipMedic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombretipmedic))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcantidad)
                    .addComponent(TextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldistribuidor)
                    .addComponent(RadioButCofarma)
                    .addComponent(RadioButEmpsephar)
                    .addComponent(RadButCemefar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsucursal)
                    .addComponent(CheckBoxPrincipal)
                    .addComponent(CheckBoxSecundaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttborrar)
                    .addComponent(buttconfirmar))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        RadioButCofarma.getAccessibleContext().setAccessibleName("OpCofarma");
        RadioButEmpsephar.getAccessibleContext().setAccessibleName("OpEmpsephar");
        RadButCemefar.getAccessibleContext().setAccessibleName("OpCemefar");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxPrincipalActionPerformed

    private void RadioButCofarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButCofarmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButCofarmaActionPerformed

    private void RadioButEmpsepharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButEmpsepharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButEmpsepharActionPerformed

    private void CheckBoxSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxSecundariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxSecundariaActionPerformed

    private void buttborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttborrarActionPerformed
// Limpia los campos de texto
    txtmedic.setText("");
    TextCantidad.setText("");
    
    // Restablece el desplegable a la primera opción
    ComboBoxTipMedic.setSelectedIndex(0);
    
    // Desmarca las opciones de distribuidor (ButtonGroup)
    if (Distribuidores != null) {
        Distribuidores.clearSelection();
    }
    
    // Desmarca los CheckBox de sucursal
    CheckBoxPrincipal.setSelected(false);
    CheckBoxSecundaria.setSelected(false);     // TODO add your handling code here:
    }//GEN-LAST:event_buttborrarActionPerformed

    private void buttconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttconfirmarActionPerformed
    String nombre = txtmedic.getText().trim();
    String tipo = (String) ComboBoxTipMedic.getSelectedItem();
    String cantidadTxt = TextCantidad.getText().trim();  
    
    if (nombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Debe ingresar el nombre del medicamento.", 
            "Error de Validación", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    int cantidad;//MENSAJES DE VALIDACION DE CANTIDAD
    try {
        cantidad = Integer.parseInt(cantidadTxt);
        if (cantidad <= 0 || cantidad >100 ) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "La cantidad debe ser un número entero positivo (entre 1 y 100).", 
                "Error de Validación", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "La cantidad de producto debe ser un NUMERO entero válido.", 
            "Error de Validación", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    // Validar selección del distribuidor
    String distribuidor = null;
    if (RadioButCofarma.isSelected()) {
        distribuidor = "Cofarma";
    } else if (RadioButEmpsephar.isSelected()) {
        distribuidor = "Empsephar";
    } else if (RadButCemefar.isSelected()) {
        distribuidor = "Cemefar";
    }

    if (distribuidor == null) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Debe elegir un distribuidor farmacéutico.", 
            "Error de Validación", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // 4. Validar selección de sucursal (Principal, Secundaria o ambas)
    boolean esPrincipal = CheckBoxPrincipal.isSelected();
    boolean esSecundaria = CheckBoxSecundaria.isSelected();

    if (!esPrincipal && !esSecundaria) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Debe elegir al menos una sucursal (Principal y/o Secundaria).", 
            "Error de Validación", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    Medicamento medicamento = new Medicamento(nombre, tipo, cantidad, distribuidor, esPrincipal, esSecundaria);
    VentanaPedido resumen = new VentanaPedido(medicamento);
    resumen.setVisible(true);
    }//GEN-LAST:event_buttconfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxPrincipal;
    private javax.swing.JCheckBox CheckBoxSecundaria;
    private javax.swing.JComboBox<String> ComboBoxTipMedic;
    private javax.swing.ButtonGroup Distribuidores;
    private javax.swing.JRadioButton RadButCemefar;
    private javax.swing.JRadioButton RadioButCofarma;
    private javax.swing.JRadioButton RadioButEmpsephar;
    private javax.swing.JTextField TextCantidad;
    private javax.swing.JButton buttborrar;
    private javax.swing.JButton buttconfirmar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNombreFarmacia;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JLabel lbldistribuidor;
    private javax.swing.JLabel lblnombremec;
    private javax.swing.JLabel lblnombretipmedic;
    private javax.swing.JLabel lblsucursal;
    private javax.swing.JTextField txtmedic;
    // End of variables declaration//GEN-END:variables

    private void SetLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
