/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CELESTE
 */
public class VentanaPedido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPedido.class.getName());

    /**
     * Creates new form VentanaPedido
     */
    public VentanaPedido(Medicamento med) {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(179, 235, 235));
        lblNombreFarmacia1.setOpaque(true);
        lblNombreFarmacia1.setBackground(java.awt.Color.WHITE);
        lbldetaltitl.setOpaque(true);
        lbldetaltitl.setBackground(java.awt.Color.WHITE);
        labletitdir.setOpaque(true);
        labletitdir.setBackground(java.awt.Color.WHITE);
        
        
        
        
        // Asigna el título de la ventana con el distribuidor correspondiente
        setTitle("Pedido al distribuidor " + med.getDistribuidor());
        
        // Muestra los datos recopilados en las etiquetas de la interfaz
        lblDetalle.setText(med.getTextoDetalle());
        lblDireccion.setText("<html><div style='text-align: center; width: 300px;'>" + med.getTextoDireccion() + "</div></html>");
        
        // Centra la ventana emergente en pantalla
        setLocationRelativeTo(null);
    }

    // Constructor 2: Sin parámetros (mantiene la compatibilidad con el método main)
    public VentanaPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreFarmacia1 = new javax.swing.JLabel();
        lblDetalle = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnEnviar = new javax.swing.JButton();
        lbldetaltitl = new javax.swing.JLabel();
        labletitdir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNombreFarmacia1.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreFarmacia1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNombreFarmacia1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreFarmacia1.setText("FARMACIA CELESTE S.A.S");
        lblNombreFarmacia1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDetalle.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDetalle.setText("Detalle");

        lblDireccion.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDireccion.setText("Direccion");

        BtnCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        BtnCancelar.setText("CANCELAR");
        BtnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCancelar.addActionListener(this::BtnCancelarActionPerformed);

        BtnEnviar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        BtnEnviar.setText("ENVIAR");
        BtnEnviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnEnviar.addActionListener(this::BtnEnviarActionPerformed);

        lbldetaltitl.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbldetaltitl.setText("DETALLES:");
        lbldetaltitl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labletitdir.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        labletitdir.setText("DIRECCION:");
        labletitdir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblNombreFarmacia1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(BtnCancelar)
                        .addGap(103, 103, 103)
                        .addComponent(BtnEnviar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldetaltitl)
                            .addComponent(labletitdir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion)
                            .addComponent(lblDetalle))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblNombreFarmacia1)
                .addGap(38, 38, 38)
                .addComponent(lbldetaltitl)
                .addGap(18, 18, 18)
                .addComponent(lblDetalle)
                .addGap(89, 89, 89)
                .addComponent(labletitdir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(lblDireccion)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnEnviar))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
     this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnviarActionPerformed
    System.out.println("PEDIDO ENVIADO"); // Simulación del envío requerida por la guía
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEnviar;
    private javax.swing.JLabel labletitdir;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombreFarmacia1;
    private javax.swing.JLabel lbldetaltitl;
    // End of variables declaration//GEN-END:variables
}
